[package]
name = "vasak-permissions-agent"
description = "VasakOS permission dialog agent"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "vasak_permissions_agent_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "vasak-permissions-agent"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
vasak-permissions-protocol.workspace = true
tauri = { version = "2", features = [] }
tauri-plugin-vicons = "2"
tauri-plugin-config-manager = "2"
tauri-plugin-i18n-vsk = "2.1.1"
serde.workspace = true
serde_json.workspace = true
zbus.workspace = true
tokio.workspace = true
